; PlatformIO project for an ESP32-S3 USB HID macropad
; Docs: https://docs.platformio.org/en/latest/projectconf/

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1   ; change if you have a different S3 board variant
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem31101
monitor_port = /dev/cu.usbmodem31101
build_flags =
    -D ARDUINO_USB_MODE=0        ; USB-OTG/TinyUSB mode, required for USBHIDKeyboard/USBHIDConsumerControl
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; also expose a serial console over the same port, for debugging
